### ISSUE TITLE
Bash error with complex search pattern

### ISSUE THREAD

**Issue by tissieres** [qalshidi/vim-bettergrep#2]
Hello, 

First thanks for your plugin!

When I search for a pattern like `'"example", \['` that works well with ripgrep in command-line, it generates a bash syntax error with the function `Grep` of your plugin.

**Comment by qalshidi** [comment]
Thanks for letting me know, I'll get to it as quick as I can.

**Comment by qalshidi** [comment]
Unfortunately, because of how vim takes commands, a workaround seems to be to do `'\\"example\\", \['` is this okay?

**Comment by tissieres** [comment]
Well, if there is no other solution, I will try to remember to double-escape the quotes. Thanks for looking into this!
