### ISSUE TITLE
Vim bettergrep not searching anything

### ISSUE THREAD

**Issue by sansyrox** [qalshidi/vim-bettergrep#4]
This plugin is not searching anything for anything.

It used to run well and suddenly it stopped searching for anything.

It is also not outputting an error. How do I debug the issue?

**Comment by qalshidi** [comment]
It would be helpful if you include your set up and the error you are facing.

1. What is your operating system, vim version?
2. Which grep program are you trying to use?
3. What are your relevant `vimrc` or `init.vim` lines?

**Comment by sansyrox** [comment]
Hi @qalshidi ,
Thank you for the revert. I am trying to use `ripgrep` for this. This is my vim config(https://github.com/sansyrox/macsimus/) .

**Comment by sansyrox** [comment]
Now, that I try with `git grep` it is working. What should put in here `let g:bettergrepprg = "<some_grepper>"
` for ripgrep to work?

**Comment by qalshidi** [comment]
Usually it will auto-configure ripgrep by itself, but if you want to explicitly do it then:

```
let g:bettergrepprg = "rg --vimgrep"
```

should suffice

**Comment by sansyrox** [comment]
Hey @qalshidi ,

I tried adding this, but this doesn't work. Is there a possibility to get debug logs?

**Comment by qalshidi** [comment]
Can you please let me know the error message? "this doesn't work" is not very helpful. If there is no error message can you be clear on the behavior. Does it simply find nothing?

**Comment by sansyrox** [comment]
@qalshidi , that is the issue. It doesn't give out an error message. It doesn't return any search results.

When I use Rg in FZF, it then gives out a correct result.

**Comment by qalshidi** [comment]
Keep in mind it works on my setup but not yours. So can you make a reproducible set up so that I may test why it's not working? Also what OS and vim version are you using?

**Comment by sansyrox** [comment]
@qalshidi , I using `macOS 11.4 20F71 x86_64` and `NVIM v0.6.0-dev+1490-g3de777d25
Build type: Release`

**Comment by sansyrox** [comment]
@qalshidi , you can install it using this command 
```
bash <(curl -s https://raw.githubusercontent.com/sansyrox/macsimus/main/utils/install.sh)

```

This is my neovim config: https://github.com/sansyrox/macsimus/

**Comment by qalshidi** [comment]
I think I know your issue. You may be searching in a folder with a very large amount of text. If `git grep` works better then `rg` is probably ignoring the vcs and taking a while to return with results since it runs asynchronously. Try:

1. Creating a new folder.
2. `echo 'this is a test' > file.txt
3. `nvim`
4. `:Grep test`

And that should work as expected with ripgrep.

Can you tell me where exactly have you tested this with? Have you tried it in a simple folder like I showed?

**Comment by sansyrox** [comment]
Hi @qalshidi , sorry for the late revert.

I tried this. Even with a single file with a single line, ripgrep doesn't work.

**Comment by qalshidi** [comment]
When you do the single file with a single line what does `:pwd` output in Neovim?

**Comment by sansyrox** [comment]
@qalshidi , `:pwd` shows the name of that directory only. But something strange has happened now. Even "Grep" has stopped working.

**Comment by sansyrox** [comment]
However, `GrepperRg` works.

**Comment by qalshidi** [comment]
I have checked the code for `:GrepperRg` and made some fixes that may work. Please update your `vim-bettergrep` and try again.

**Comment by sansyrox** [comment]
@qalshidi , it is still not working for me. I'll try to run it on a fresh neovim install and see if it works.

**Comment by qalshidi** [comment]
Closed.
